main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('cerita/', views.cerita, name='cerita' ),
    path('kontak/', views.kontak, name='kontak'),
    path('tentang/', views.tentang, name='tentang'),
    path('proyek/', views.proyek, name='proyek'),
    path('gallery/', views.gallery, name='gallery'),
    path('kegiatan/', views.kegiatan, name='kegiatan'),
    path('kegiatan/add', views.addMatkul, name='add'),
    path('tabel_matkul/', views.tabelmatkul, name='tabelmatkul'),
    path('kegiatan/tambahdosen', views.utambahdosen, name='tambahdosen'),
    path('kegiatan/tambahdoseny', views.tambahdosen, name='tambahdoseny'),
    path('<int:pk>', views.deletematkul, name='Delete')
]

story4_ppwdjango/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story6ppw/', include('story6_ppw.urls')),
    path('story8ppw/', include('story8.urls')),
    path('story9/', include('story9.urls')),
    path('', include('main.urls')),
]

story8/urls.py
from django.urls import path

from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.hm, name='hm'),
    path('data/', views.data_function)
]

story9/urls.py
from django.urls import path

from . import views

app_name = 'story9'

urlpatterns = [
    path('login', views.logink, name='logink'),
    path('logout', views.logoutk, name='logoutk'),
    path('signup', views.signup, name='signupk'),
    path('', views.redlogin, name='redlogin'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<a class="navbar-brand" href="#"> <img src="{% static 'img/my_name.jpg' %}" > </a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse justify-content-end" id="navbarNav">
			<ul class="navbar-nav">
				<li class="nav-item ">
					<a class="nav-link" href="{% url 'main:home' %}">Home</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'main:tentang' %}">Tentang
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'main:cerita' %}">Story Satu
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'main:proyek' %}">Proyek
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'main:gallery' %}">Gallery</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'main:kontak' %}">Kontak</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'main:tabelmatkul' %}">Tabel Kuliah</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'main:kegiatan' %}">Kegiatan Kuliah</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'story8:hm' %}">Story 8</a>
				</li>
				{% if not user.is_authenticated %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'story9:logink' %}">Login</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'story9:signupk' %}">Sign Up</a>
				</li>
				{% else %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'story9:logoutk' %}">Logout    [username = {{user.username}} ]</a>
				</li>
				{% endif %}
			</ul>
		</div>
	</nav>
  {% block content %}
  {% endblock content %}
</body>

</html>