main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('cerita/', views.cerita, name='cerita' ),
    path('kontak/', views.kontak, name='kontak'),
    path('tentang/', views.tentang, name='tentang'),
    path('proyek/', views.proyek, name='proyek'),
    path('gallery/', views.gallery, name='gallery'),
    path('kegiatan/', views.kegiatan, name='kegiatan'),
    path('kegiatan/add', views.addMatkul, name='add'),
    path('tabel_matkul/', views.tabelmatkul, name='tabelmatkul'),
    path('kegiatan/tambahdosen', views.utambahdosen, name='tambahdosen'),
    path('kegiatan/tambahdoseny', views.tambahdosen, name='tambahdoseny'),
    path('<int:pk>', views.deletematkul, name='Delete')
]

story4_ppwdjango/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story6ppw/', include('story6_ppw.urls')),
    path('story8ppw/', include('story8.urls')),
    path('story9/', include('story9.urls')),
    path('', include('main.urls')),
]

main/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Dosen(models.Model):
	first_name = models.CharField(max_length=40)
	last_name = models.CharField(max_length=40,blank=True)

	def __str__(self):
		return "{0} {1}".format(self.first_name, self.last_name)

class Day(models.Model):
	name = models.CharField(max_length=30)

	def __str__(self):
		return self.name

class MataKuliah(models.Model):
	GS_2020 = 'Gasal 2020/2021'
	GN_2019 = 'Genap 2019/2020'
	GS_2019 = 'Gasal 2018/2019'
	GN_2018 = 'Genap 2018/2019'
	GS_2018 = 'Gasal 2018/2019'
	GN_2017 = 'Genap 2017/2018'

	SEMESTER_TAHUN_CHOICES = ((GS_2020, 'Gasal 2020/2021'), (GN_2019, 'Genap 2019/2020'), (GS_2019, 'Gasal 2019/2020'), (GN_2018, 'Genap 2018/2019'), (GS_2018, 'Gasal 2018/2019') ,(GN_2017, 'Genap 2017/2018'))

	semester_tahun = models.CharField(max_length=40, choices=SEMESTER_TAHUN_CHOICES, blank=False, default=GS_2020)
	name = models.CharField(max_length=50)
	sks = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(20)])
	deskripsi_text = models.CharField(max_length=400)
	ruang_kelas = models.CharField(max_length=100)
	dosen_kuliah = models.ManyToManyField(Dosen)
	days = models.ManyToManyField(Day)

	def __str__(self):
		return "{0} {1}".format(self.name, self.semester_tahun)

main/forms.py
from django import forms
from django.forms import ModelForm
from .models import Dosen, Day, MataKuliah
from .admin import *


class DosenForm(forms.ModelForm):

	class Meta:
		model = Dosen
		fields = ('first_name','last_name') 
		help_texts = {'first_name':'Isi nama pertama.', 'last_name':'Isi nama terakhir.'}

class MataKuliahForm(forms.ModelForm):

	deskripsi_text = forms.CharField( widget=forms.Textarea)
	days = forms.ModelMultipleChoiceField(queryset=Day.objects, required=True)

	class Meta:
		model = MataKuliah
		fields = ['name','semester_tahun','sks','deskripsi_text','ruang_kelas','dosen_kuliah','days']

class DayForm(forms.ModelForm):

	class Meta:
		model = Day
		fields = ['name']

main/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST 
from .models import MataKuliah as matkul
from .models import Dosen as dosenk
from .models import Day as day
from .forms import DosenForm, MataKuliahForm, DayForm

def home(request):
    return render(request, 'main/home.html')

def cerita(request):
	return render(request, 'main/ceritasatu.html')

def kontak(request):
	return render(request, 'main/kontak.html')

def tentang(request):
	return render(request, 'main/tentang.html')

def gallery(request):
	return render(request, 'main/gallery.html')

def proyek(request):
	return render(request, 'main/proyek.html')

def kegiatan(request):
    form_mk = MataKuliahForm()

    context = {'form_mk' : form_mk, 'mylink' : True, 'number': 1}

    return render(request, 'main/kegiatan.html', context)

def utambahdosen(request):
    form_mk = DosenForm()

    context = {'form_mk' : form_mk, 'mylink' : False, 'number': 2}

    return render(request, 'main/kegiatan.html', context)

def tabelmatkul(request):
	matakuliah = matkul.objects.all()

	context = {"matakuliah" : matakuliah}

	return render(request, 'main/tabelmatakuliah.html', context)


def deletematkul(request, pk):
	matkul.objects.filter(pk=pk).delete()
	new_data = matkul.objects.all()
	context = {"matakuliah": new_data} 
	return render(request, 'main/tabelmatakuliah.html', context)

@require_POST
def addMatkul(request):
	form_mk = MataKuliahForm(request.POST)
	if form_mk.is_valid():
		mk = matkul()
		mk = form_mk.save(commit=False)
		mk.save()
		form_mk.save_m2m()
		return redirect('/cerita')
	else:
		print('Invalid Form')

	return redirect('/cerita')

@require_POST
def tambahdosen(request):
	form_mk = DosenForm(request.POST)
	if form_mk.is_valid():
		mk = matkul()
		mk = form_mk.save(commit=False)
		mk.save()
		return redirect('/cerita')
	else:
		print('Invalid Form')
	return redirect('/cerita')

main/templates/main/ceritasatu.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Cerita Satu PPW</title>
{% endblock meta %}

{% block content %}
<div class="my-first-content" id = "cerita-satu">
                <div id = "cerita-satu-content">
                    <h1>Cerita Satu</h1>
                    <p>Inilah penyelesaian tugas satu.</p>
                    <img src="{% static 'img/fotoSaya.jpg' %}" id= "fotopribadi" alt="Foto saya">

    <br> <b>Nama :  </b>
    Vander Gerald </br>
    <b>Tempat Kuliah :</b>
    Fasilkom UI </br>
    <b>Jurusan :</b>
    Ilmu Komputer </br>
    <b>NPM :</b>
    1906350603 </br>
    <b>Angkatan :</b>
    2019 </br>
    <b>Hobi :</b>
    catur, membaca buku </br>

<h2> Deskripsi Diri </h2>
<p>Saat ini saya seorang mahasiswa ilmu komputer yang siap belajar berbagai masalah komputer yang harus diselesaikan dan membuat saya berpikir. Saya berpikir bahwa saya memiliki gagasan yang cukup baik tentang jenis masalah yang mungkin saya hadapi dalam jurusan ilmu komputer ini. Saya percaya saya bisa menyelesaikan studi saya dengan efektif dan itulah tujuan saya saat ini.
</p>
<p>Saya belajar dengan cara saya sendiri untuk memiliki kemampuan dan pengetahuan <i>programming</i> yang baik di masa depan. 
    Hal tersebut menjadi bagian yang sangat penting dari kehidupan saya untuk beberapa tahun ke depan.</p>
<h2>Riwayat Pendidikan</h2>
<table class="table">
    <thead>
    <tr>
    <th scope="col"># </th>
        <th scope="col">Tahun </th>
        <th scope="col">Nama Institusi</th>
    </tr>
    </thead>
    <tbody>
    <tr>
    <th scope="row"> 1 </th>
        <td> 2013 - 2016</td>
        <td> SMPK Penabur Kota Tangerang</td>
    </tr>
    <tr>
    <th scope="row"> 2 </th>
        <td> 2016 - 2019 </td>
        <td> SMAK Penabur Kota Tangerang</td>
    </tr>
    <tr>
    <th scope="row"> 3 </th>
        <td> 2019 - sekarang </td>
        <td> Universitas Indonesia</td>
    </tr>
    </tbody>
</table>
         </div>
</div>

    
{% endblock content %}

main/templates/main/gallery.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Gallery</title>
{% endblock meta %}


{% block content %}
  <div class="my-first-content">
           <div id="gallery-contant">

                <div id = "Gallery">
                    <h2>Gallery</h2>
                    <p> Kita ingin mengisi gallery ini. 
                    </p>

                    <div class="just-display-container">  
  <img class="yourSlides" src="{% static 'img/s1.jpg' %}">
  <img class="yourSlides" src="{% static 'img/s2.jpg' %}">
  <img class="yourSlides" src="{% static 'img/s3.jpg' %}">
  <img class="yourSlides" src="{% static 'img/s4.jpg' %}">
  <img class="yourSlides" src="{% static 'img/s5.jpg' %}">

  <button class="our-button display-left" onclick="tambahIndex(-1)">&#10094;</button>
  <button class="our-button display-right" onclick="tambahIndex(1)">&#10095;</button>
  <script src="{% static 'js/simpleimageslider.js' %}"> </script>
  
 </div>
                
     </div>
        </div>  
  
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Homepage</title>
{% endblock meta %}


{% block content %}
   <div class="my-first-content" id = "homecontent">
           <h2>Selamat Datang di Homepage</h2>
            <div id="teks">
                <div id = "homepg">
                    <p> Nama saya Vander Gerald Sukandi. Nomor pokok mahasiswa 1906350603. </p>
                    <p>
                        Saya senang Anda telah menemukan homepage website ini dan ingin mengetahui sesuatu tentang saya. Terima kasih. 
                        Saat ini, saya harus menyelesaikan tugas Perancangan dan Pemrograman Web dengan Django.</p>
                    

                </div>
        </div>
    </div>
{% endblock content %}

main/templates/main/kegiatan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Kegiatan Kuliah</title>
{% endblock meta %}


{% block content %}
  <div class="my-first-content">
                <div id = "Kegiatan-Ku">

                  {% if number == 1 %}
                    <h2>Form Mata Kuliah</h2>
                  {% elif number == 2 %}
                   <h2>Form Dosen</h2>
                  {% endif %}
                    {% if mylink %}
                  <li class="nav-item" id ="tambah-ds" >
                    <a class="nav-link" href="{% url 'main:tambahdosen' %}">Tambah Dosen</a>
                  </li>
                  {% endif %}

                    <div class="form-khusus">
                      <p> Isi form di bawah ini.</p>
                      {% if number == 1 %}
                      <form action="add" method="POST">
                  {% elif number == 2 %}
                      <form action="tambahdoseny" method="POST">
                  {% endif %}
                        {% csrf_token %}
                        <table border="1">
                             {% for field in form_mk %}
    {{ field.errors }}
    <li> {{ field.label_tag }} {{ field }} </li> 
  {% endfor %}
                         </table>
                        <input type="submit" class='btn btn-primary' value="Add ">
                      </form>
 </div>  
 <p> Akhir halaman </p>     
     </div>
        </div>  

{% endblock content %}

main/templates/main/kontak.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Kontak</title>
{% endblock meta %}


{% block content %}
   <div class="left-content" id = "contact-form-content">
           <div class="my-first-content" id="l-content-contact">
            <div class="pertanyaan" id = "pertanyaan-kontak">
                <h2>Ada pertanyaan?</h2>

                <p>Ada pertanyaan? </p>
                <p> Silahkan  hubungi saya dengan mengisi form di bawah ini. Semua e-mail dienkripsi dan dikirim dengan aman.</p>
            </div>
        </div>      
        </div>  

        <div id="right-content">
    
            <div class="my-first-content" id = "right-contacts">
                    <h1>Hubungi Vander Gerald </h1>
                    <b>Nomor telepon</b>
                    <p>+628 2279 302 001</p>
                    <b>E-mail universitas</b>
                    <p>vander.gerald@ui.ac.id</p>
                    <b>E-mail pribadi</b>
                    <p>vndrgrld2001@gmail.com</p>
                    <b>Gitlab <img id = "gitlab" src= "{% static 'img/gitlab.jpg' %}"> </b>
                    <p> <a href="https://gitlab.com/v_gerald"> Gitlab saya </a> </p>
                    <b>Line</b>
                    <p>@vanderrz</p>
            </div>

        </div>

{% endblock content %}

main/templates/main/proyek.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title></title>
{% endblock meta %}


{% block content %}
   <div class="my-first-content" id = "projectcontent">
           <h2>Selamat Datang di halaman Proyek</h2>
            <div id="teks">
                <div id = "homepg">
                    <p> Halaman ini belum bisa diisi. </p>
                    

                </div>
        </div>
    </div>
{% endblock content %}

main/templates/main/tabelmatakuliah.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Tabel Mata Kuliah</title>
{% endblock meta %}


{% block content %}
  <div class="my-first-content">
                    <div class="form-khusus">
                      <h1>Tabel Mata Kuliah </h1>
                        <table class="table" border="1">
                          <thead>
                          <tr>
                        <th scope = "col"> Nama </th>
                        <th scope = "col"> Semester </th>
                        <th scope = "col"> SKS </th>
                        <th scope = "col"> Deskripsi </th>
                        <th scope = "col"> Ruang Kelas </th>
                        <th scope = "col"> Dosen Kuliah </th>
                        <th scope = "col"> Hari </th>
                        <th scope = "col"> Hapus </th>

                      </tr>
                    </thead>
                    <tbody>
                      {% for matkul in matakuliah %} 
                      <tr>
                        <th scope ="row"> {{matkul.name}} </th>
                        <th scope ="row"> {{matkul.semester_tahun}} </th>
                        <th scope ="row"> {{matkul.sks}} </th>
                        <th scope ="row"> {{matkul.deskripsi_text}} </th>
                        <th scope ="row"> {{matkul.ruang_kelas}} </th>
                        <th scope ="row">{% for dosen in matkul.dosen_kuliah.all %}<li>{{dosen}} </li>
                        {% endfor %} 
                      </th>
                        <th scope ="row"> {% for hari in matkul.days.all %}
                          <li>{{days}} </li> {% endfor %} 
                           </th> 
                        <td><a href = " {% url 'main:Delete' pk=matkul.pk %}"> <button class = "btn btn-icon btn-danger"> </td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                       
 </div>    
     </div>

{% endblock content %}

main/templates/main/tentang.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Tentang Saya</title>
{% endblock meta %}


{% block content %}
   <div class="my-first-content" id = "tentang-saya">            
            <div id="teks">
                <div id = "Tentang">
                    <h1>Tentang Saya</h1>

                    <p> Saya lahir di Tangerang, Indonesia pada 9 Juni 2001. 
                        Saya dibesarkan oleh kedua orangtua saya di kota ini. Nama lengkap saya adalah Vander Gerald Sukandi. 
                        Saya  warga negara Indonesia keturunan Tionghoa generasi ketiga dari pihak ayah dan keturunan Manado generasi kesekian dari pihak ibu. Saya anak tunggal. 
                    </p>
                    <div id="fotol">
                        <img src="{% static 'img/fotoSaya.jpg' %}" alt="Vander Gerald" height="180px" width="180px"/> 
                    </div>
                    <p>
                        Saya lulus dari SMAK Penabur Kota Tangerang, saya mengikuti SBMPTN 2019 dan setelah memasuki perkuliahan di Fakultas Ilmu Komputer UI sebagai mahasiswa jurusan Ilmu Komputer pada tahun 2019. Di semester tiga ini, saya harus menyelesaikan mata kuliah wajib Perancangan dan Pemrograman Web yang notabenenya membebani dengan tugas setiap minggu. Prototype ini dibuat  untuk menyelesaikan tugas 2.
                    </p>
                    <p>Setiap orang tentu memiliki hobi pribadi. Bagi saya, hobi saya adalah bermain catur. Bermain catur membuat saya bugar secara mental. Pemakaian otak saya dalam permainan catur membiasakan diri saya dengan pengambilan keputusan yang cepat. Hobi saya ini memilki sifat kompetitif dan aturan-aturan yang baku. Saya tertarik pada permainan ini dan memutuskan untuk mempelajarinya sejak tahun ketiga sekolah dasar saya. Saya menekuninya sampai saya menjadi pemain catur terbaik di SMA saya dulu dan memenangkan satu lomba catur  tingkat nasional di Jakarta.</p>
                    <p> Saya punya pemikiran bahwa setelah lulus kuliah saya bisa bekerja sebagai pemrogram komputer. Saya cukup menyukai pemrograman komputer dan siap mempelajari apapun yang diperlukan. Saya mampu bekerja keras dan menolerir kebosanan demi keberhasilan.
                    </p>
                </div>
        </div>
    </div>

{% endblock content %}